plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://language-machine.github.io
baseurl: /fireworksr

title: Language Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Language-Machine
  verb: Language
  instructions_file: language.md
  token: fireworks
  server: https://localhost:443
  apiUrl: https://api.fireworks.ai/inference/v1/chat/completions

app:
  worker_name: fireapi.js

lm:
  model: glm-5p3
  max_tokens: 32000
  reasoning_effort: high
  prompt_truncate_len: 10000
  temperature: 1.0
  top_p: 0.7
  top_k: 50
